import {
  ApplicationConfig,
  provideZoneChangeDetection,
  importProvidersFrom,
  LOCALE_ID,
} from '@angular/core';
import {
  provideHttpClient,
  withInterceptorsFromDi,
  HTTP_INTERCEPTORS,
} from '@angular/common/http';
import { routes } from './app.routes';
import {
  provideRouter,
  withComponentInputBinding,
  withInMemoryScrolling,
} from '@angular/router';
import { provideAnimationsAsync } from '@angular/platform-browser/animations/async';
import { provideClientHydration } from '@angular/platform-browser';
import { AuthInterceptor } from './services/auth-interceptor.service';
import { LoadingInterceptor } from './shared/interceptors/loading.interceptor';
import { GoogleDriveAuthInterceptor } from './shared/interceptors/google-drive-auth.interceptor';
import { MAT_DATE_LOCALE } from '@angular/material/core';
import { provideIcons } from '@ng-icons/core';
import {
  tablerBrandDribbble,
  tablerBrandFacebook,
  tablerBrandGithub,
  tablerBrandLinkedin,
  tablerBrandTwitter,
  tablerBrandX,
  tablerBrandYoutube,
  tablerBook,
  tablerBug,
  tablerCalendar,
  tablerChartBar,
  tablerChecklist,
  tablerComponents,
  tablerBriefcase,
  tablerChevronDown,
  tablerDeviceDesktop,
  tablerDots,
  tablerDotsVertical,
  tablerEdit,
  tablerEye,
  tablerFileDescription,
  tablerHeart,
  tablerLayoutDistributeHorizontal,
  tablerLayoutDistributeVertical,
  tablerLayoutNavbar,
  tablerLayoutSidebar,
  tablerLayoutSidebarRight,
  tablerMail,
  tablerMapPin,
  tablerMessage2,
  tablerMessageCircle,
  tablerMoon,
  tablerPhoto,
  tablerPlus,
  tablerPoint,
  tablerRocket,
  tablerSearch,
  tablerSend,
  tablerShadow,
  tablerShadowOff,
  tablerShare,
  tablerSunHigh,
  tablerTextDirectionLtr,
  tablerTextDirectionRtl,
  tablerThumbUp,
  tablerTrash,
  tablerUserCheck,
  tablerUserCircle,
  tablerWorld,
  tablerX,
  tablerLayoutGrid,
  tablerLayoutKanban,
  tablerLayoutList,
  tablerLayoutBoard,
} from '@ng-icons/tabler-icons';

// perfect scrollbar
import { NgScrollbarModule } from 'ngx-scrollbar';

//Import all material modules
import { MaterialModule } from './material.module';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';

export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(
      routes,
      withInMemoryScrolling({
        scrollPositionRestoration: 'enabled',
        anchorScrolling: 'enabled',
      }),
      withComponentInputBinding()
    ),
    provideHttpClient(withInterceptorsFromDi()),
    { provide: HTTP_INTERCEPTORS, useClass: AuthInterceptor, multi: true },
    { provide: HTTP_INTERCEPTORS, useClass: LoadingInterceptor, multi: true },
    { provide: HTTP_INTERCEPTORS, useClass: GoogleDriveAuthInterceptor, multi: true },
    { provide: LOCALE_ID, useValue: 'fr-FR' },
    { provide: MAT_DATE_LOCALE, useValue: 'fr-FR' },
    provideClientHydration(),
    provideAnimationsAsync(),
    provideIcons({
      tablerBrandDribbble,
      tablerBrandFacebook,
      tablerBrandGithub,
      tablerBrandLinkedin,
      tablerBrandTwitter,
      tablerBrandX,
      tablerBrandYoutube,
      tablerBook,
      tablerBug,
      tablerCalendar,
      tablerChartBar,
      tablerChecklist,
      tablerComponents,
      tablerBriefcase,
      tablerChevronDown,
      tablerDeviceDesktop,
      tablerDots,
      tablerDotsVertical,
      tablerEdit,
      tablerEye,
      tablerFileDescription,
      tablerHeart,
      tablerLayoutDistributeHorizontal,
      tablerLayoutDistributeVertical,
      tablerLayoutNavbar,
      tablerLayoutSidebar,
      tablerLayoutSidebarRight,
      tablerMail,
      tablerMapPin,
      tablerMessage2,
      tablerMessageCircle,
      tablerMoon,
      tablerPhoto,
      tablerPlus,
      tablerPoint,
      tablerRocket,
      tablerSearch,
      tablerSend,
      tablerShadow,
      tablerShadowOff,
      tablerShare,
      tablerSunHigh,
      tablerTextDirectionLtr,
      tablerTextDirectionRtl,
      tablerThumbUp,
      tablerTrash,
      tablerUserCheck,
      tablerUserCircle,
      tablerWorld,
      tablerX,
      tablerLayoutGrid,
    }),
    importProvidersFrom(
      FormsModule,
      ReactiveFormsModule,
      MaterialModule,
      NgScrollbarModule,
    ),
  ],
};
